[workspace]
members = [
    "core",
    "wallet/core",
    "wallet/cli",
    "wallet/native",
    "wallet/wasm",
    "consensus",
    "consensus/core",
    "consensus/pow",
    "kaspad",
    "simpa",
    "wasm",
    "math",
    "crypto/hashes",
    "crypto/muhash",
    "crypto/addresses",
    "crypto/merkle",
    "rpc/core",
    "rpc/grpc",
    "rpc/macros",
    "rpc/wrpc/client",
    "rpc/wrpc/server",
    "rpc/wrpc/proxy",
]

[workspace.package]
version = "0.1.0"
authors = ["Kaspa developers"]
license = "MIT/Apache-2.0"
edition = "2021"
include = ["src/**/*.rs", "Cargo.toml"]

[workspace.dependencies]
kaspa-core = { path = "core" }
# kaspa-wallet = { path = "wallet" }
consensus = { path = "consensus" }
consensus-core = { path = "consensus/core" }
kaspad = { path = "kaspad" }
math = { path = "math" }
hashes = { path = "crypto/hashes" }
muhash = { path = "crypto/muhash" }
addresses = { path = "crypto/addresses" }
merkle = { path = "crypto/merkle" }
pow = { path = "consensus/pow" }
kaspa-utils = { path = "utils" }
rpc-core = { path = "rpc/core" }
rpc-grpc = { path = "rpc/grpc" }
kaspa-rpc-macros = { path = "rpc/macros" }
kaspa-wrpc-client = { path = "rpc/wrpc/client" }
kaspa-wrpc-server = { path = "rpc/wrpc/server" }
kaspa-wrpc-proxy = { path = "rpc/wrpc/proxy" }
kaspa-wallet-core = { path = "wallet/core" }
kaspa-wallet-cli = { path = "wallet/cli" }
kaspa-wallet-cli-native = { path = "wallet/native" }
kaspa-wallet-cli-wasm = { path = "wallet/wasm" }
kaspa-wasm = { path = "wasm" }

thiserror = "1"
faster-hex = "0.6"
itertools = "0.10"
rand = "0.8"
rand_chacha = "0.3"
rayon = "1"
tempfile = "3.3"
serde = { version = "1", features = ["derive", "rc"] }
futures-util = { version = "0.3", default-features = false, features = [
    "alloc",
] }
futures = { version = "0.3" }
bincode = { version = "1", default-features = false }
tokio = { version = "1", features = ["sync","rt-multi-thread"] }
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
criterion = { version = "0.4", default-features = false }
indexmap = "1.9.1"
smallvec = { version = "1.10.0", features = ["serde"] }
borsh = "0.10.0"
clap = { version = "4.0.23", features = ["derive"] }
async-std = { version = "1.12.0", features = ['attributes'] }
derive_more = { version = "0.99" }
log = "0.4"
cfg-if = "1.0.0"
async-trait = "0.1.57"
paste = "1.0.11"
regex = "1.6.0"
pad = "0.1.6"
convert_case = "0.5.0"
wasm-bindgen-futures="0.4.33"
js-sys = "0.3.56"

workflow-core = { path = "../workflow-rs/core" }
workflow-websocket = { path = "../workflow-rs/websocket" }
workflow-rpc = { path = "../workflow-rs/rpc" }
workflow-log = { path = "../workflow-rs/log" }
workflow-terminal = { path = "../workflow-rs/terminal" }
workflow-wasm = { path = "../workflow-rs/wasm" }