[package]
name = "kaspa-wallet"
version = "0.1.0"
edition = "2021"

[dependencies]
kaspa-wallet-cli.workspace = true
workflow-terminal.workspace = true
workflow-log.workspace = true
async-std.workspace = true
async-trait.workspace = true
tokio.workspace = true
