[package]
name = "kaspa-wasm-types"
description = "Kaspa core WASM32 types"
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
license.workspace = true
repository.workspace = true

[features]
wasm32-sdk = []

[dependencies]
wasm-bindgen.workspace = true
