

# nw.toml - for additional properties please see https://github.com/aspectron/cargo-nw

[application]
name = "kassiopeya"
version = "0.1.0"
title = "Kassiopeya"
organization = "Your Organization Name"

[description]
short = "..."
long = """
...
""""

[package]
# root = ""
# resources = "resources/setup"
# exclude = ["resources/setup"]
exclude = [{ glob = ["{src/*,target/*,test/*,resources/setup/*,*.lock,*.toml,.git*}"] }]

[node-webkit]
version = "0.71.0"
ffmpeg = false

[dmg]
# window = ["0,0,300,300"]
# icon = ["0,0"]
# applications = ["0,0"]

[windows]
uuid = "9464f462-db23-4f78-a027-c864db698121"
group = "$GROUP"
# run_on_startup = "everyone"
run_after_setup = true

# [languages]
# languages = ["english"]

# [firewall]
# application = "in:out"

