[package]
name = "kaspa-consensus-notify"
description = "Kaspa consensus notifier"
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
license.workspace = true

[dependencies]
kaspa-hashes.workspace = true
thiserror.workspace = true
kaspa-consensus-core.workspace = true
kaspa-notify.workspace = true
kaspa-core.workspace = true
kaspa-utils.workspace = true
async-channel.workspace = true
log.workspace = true
futures.workspace = true
triggered.workspace = true
derive_more.workspace = true
paste.workspace = true
cfg-if.workspace = true
