[package]
name = "kaspa-index-processor"
description = "Kaspa index processor"
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
license.workspace = true

[dependencies]
kaspa-hashes.workspace = true
kaspa-consensus-core.workspace = true
kaspa-consensus-notify.workspace = true
kaspa-core.workspace = true
kaspa-utils.workspace = true
kaspa-database.workspace = true
kaspa-notify.workspace = true
kaspa-index-core.workspace = true
kaspa-utxoindex.workspace = true
kaspa-consensusmanager.workspace = true

thiserror.workspace = true
async-channel.workspace = true
async-trait.workspace = true
log.workspace = true
futures.workspace = true
triggered.workspace = true
derive_more.workspace = true
paste.workspace = true
tokio = { workspace = true, features = [ "rt-multi-thread", "macros", "signal" ]}

[dev-dependencies]
kaspa-consensus.workspace = true
parking_lot.workspace = true
tokio = { workspace = true, features = ["rt", "macros"] }
rand = {workspace = true,  features = [ "small_rng" ]}