[package]
name = "kaspa-wrpc-proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
consensus-core.workspace = true
kaspa-wrpc-server.workspace = true
tokio.workspace = true
rpc-grpc.workspace = true
thiserror.workspace = true
rpc-core.workspace = true
# workflow_core.workspace = true
clap.workspace = true
workflow-core.workspace = true
workflow-websocket.workspace = true
workflow-rpc.workspace = true
workflow-log.workspace = true
async-trait.workspace = true
