[package]
name = "kaspa-wallet-core"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
workflow-log.workspace = true
workflow-rpc.workspace = true
thiserror.workspace = true
kaspa-wrpc-client.workspace = true
rpc-core.workspace = true
