[package]
name = "kaspa-wallet-core"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
workflow-log.workspace = true
workflow-rpc.workspace = true
workflow-core.workspace = true
thiserror.workspace = true
kaspa-notify.workspace = true
kaspa-wrpc-client.workspace = true
kaspa-rpc-core.workspace = true
kaspa-bip32.workspace = true
addresses.workspace = true
hmac.workspace = true
ripemd.workspace = true
sha2.workspace = true
zeroize.workspace = true
async-trait.workspace = true
secp256k1.workspace = true
faster-hex.workspace = true
wasm-bindgen.workspace = true
wasm-bindgen-futures.workspace = true
js-sys.workspace = true
workflow-wasm.workspace = true
consensus-core.workspace = true
serde.workspace = true
serde_json.workspace = true
borsh.workspace = true
# consensus.workspace = true
cfg-if.workspace = true
base64.workspace = true

[dependencies.web-sys]
workspace = true
features = [
    'Storage',
    'Window',
]

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
home.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
tokio.workspace = true
