[package]
name = "kaspa-wrpc-client"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
rpc-core.workspace = true
workflow-core.workspace = true
workflow-websocket.workspace = true
workflow-rpc.workspace = true
workflow-log.workspace = true
regex.workspace = true
thiserror.workspace = true
async-trait.workspace = true
serde.workspace = true
borsh.workspace = true
async-std.workspace = true
paste.workspace = true
