[package]
name = "kaspa-wrpc-client"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
# kaspa-rpc-core = { path = "../../core" }
rpc-core.workspace = true
# workflow-rpc = "0.1.2"
workflow-log = "0.1.0"
workflow-core = "0.1.0"
workflow-rpc = { path = "../../../../../workflow-rs/workflow-rpc" }
# workflow-log = { path = "../../../../workflow-log" }
# workflow-core = { path = "../../../../workflow-core" }

regex = "1.6.0"
thiserror = "1.0.32"
async-trait = "0.1.57"
serde = { version = "1.0.144" , features = ["derive"] }
borsh = "0.9.3"
async-std = { version = "1.12.0", features = ['attributes'] }
paste = "1.0.11"
