[package]
name = "kaspa-grpc-client"
description = "Kaspa gRPC client"
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
license.workspace = true

[dependencies]
thiserror.workspace = true
kaspa-notify.workspace = true
kaspa-rpc-core.workspace = true
kaspa-grpc-core.workspace = true
kaspa-utils.workspace = true
kaspa-core.workspace = true
faster-hex.workspace = true
async-channel.workspace = true
log.workspace = true
rand.workspace = true
regex.workspace = true
async-trait.workspace = true
futures.workspace = true
tonic = { workspace = true, features = ["gzip"] }
prost.workspace = true
h2.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "sync", "time"] }
tokio-stream.workspace = true
async-stream.workspace = true
triggered.workspace = true
paste.workspace = true
