[package]
name = "kaspa-p2p-flows"
description = "Kaspa p2p flows"
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kaspa-core.workspace = true
kaspa-consensus-core.workspace = true
kaspa-consensus-notify.workspace = true
kaspa-p2p-lib.workspace = true
kaspa-utils.workspace = true
kaspa-hashes.workspace = true
kaspa-muhash.workspace = true
kaspa-connectionmanager.workspace = true
kaspa-addressmanager.workspace = true
kaspa-consensusmanager.workspace = true
kaspa-mining.workspace = true
kaspa-notify.workspace = true

parking_lot.workspace = true
rand.workspace = true
thiserror.workspace = true
log.workspace = true
itertools.workspace = true
indexmap.workspace = true
async-trait.workspace = true

# futures = { workspace = true, default-features = false, features = ["alloc"] }
futures = { workspace = true, features = ["alloc"] }
tokio = { workspace = true, features = [
    "rt-multi-thread",
    "macros",
    "signal",
] }
tokio-stream = { workspace = true, features = ["net"] }
uuid = { workspace = true, features = ["v4", "fast-rng"] }
