[package]
name = "consensus-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
license.workspace = true

[dependencies]
hashes.workspace = true
muhash.workspace = true
merkle.workspace = true
math.workspace = true
thiserror.workspace = true
serde.workspace = true
faster-hex.workspace = true
smallvec.workspace = true
borsh.workspace = true
secp256k1 = { version = "0.24", features = ["global-context", "rand-std", "serde"] }
futures-util.workspace = true
itertools.workspace = true
cfg-if.workspace = true
addresses.workspace = true
getrandom.workspace = true
txscript-errors.workspace = true
async-trait.workspace = true

kaspa-core.workspace = true
serde_json.workspace = true
serde-wasm-bindgen.workspace = true
js-sys.workspace = true
wasm-bindgen.workspace = true
workflow-wasm.workspace = true
rand.workspace = true
workflow-log.workspace = true
