[package]
name = "kaspa-wrpc-server"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
tokio.workspace = true
thiserror.workspace = true
workflow-websocket.workspace = true
workflow-rpc.workspace = true
workflow-log.workspace = true
workflow-core.workspace = true
async-trait.workspace = true
rpc-core.workspace = true
kaspa-rpc-macros.workspace = true
borsh.workspace = true
paste.workspace = true
kaspa-core.workspace = true
kaspa-utils.workspace = true
futures.workspace = true