[package]
name = "kaspa-beacon"
description = "Kaspa wRPC Endpoint Monitor"
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]


ahash.workspace = true
cfg-if.workspace = true
clap.workspace = true
futures.workspace = true
kaspa-consensus-core.workspace = true
kaspa-rpc-core.workspace = true
kaspa-utils.workspace = true
kaspa-wrpc-client.workspace = true
serde_json.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
toml.workspace = true

axum = "0.7.4"
console = "0.15.8"
mime = "0.3.16"
tower = { version = "0.4.13", features = ["buffer","limit"] }
tracing-subscriber = "0.3.18"
workflow-core.workspace = true
workflow-http.workspace = true
workflow-log.workspace = true
xxhash-rust = { workspace = true }