[package]
name = "kaspa-utils"
description = "Kaspa utilities"
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
license.workspace = true

[dependencies]
async-channel.workspace = true
triggered = "0.1"