[package]
name = "kaspa-wallet-cli"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
workflow-core.workspace = true
workflow-log.workspace = true
workflow-terminal.workspace = true
kaspa-wrpc-client.workspace = true
kaspa-wallet-core.workspace = true
async-trait.workspace = true
pad.workspace = true
convert_case.workspace = true
thiserror.workspace = true
